import ChatWithUs from '@/components/ChatWithUs';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Offers from '@/components/Offers';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Bodyguard-security',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1d232a]`}
      >
        <div
          className="scrollToTop fixed right-[1rem] bottom-[4rem] md:bottom-[3rem] lg:bottom-[1.3rem] z-50"
          id="scrollToTop"
        >
          <ChatWithUs />
        </div>
        <div className="w-full m-auto bg-[#cbd2a4]">
          <Offers />
        </div>
        <div className="w-full m-auto sticky top-0 z-50  bg-[#2a323c] shadow-2xl">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
