import ChatWithUs from '@/components/ChatWithUs';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Offers from '@/components/Offers';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Bodyguard-security',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1d232a]`}
      >
        <div className="scrollToTop" id="scrollToTop">
          <ChatWithUs />
        </div>
        <Offers />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
